apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-infotrygd-poller
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
  kafka:
    pool: nav-dev
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: hm-infotrygd-proxy.dev-fss-pub.nais.io
  gcp:
    sqlInstances:
      - name: hm-infotrygd-poller-db-dev
        type: POSTGRES_12
        tier: db-f1-micro
        diskType: SSD
        highAvailability: false
        diskSize: 10
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: infotrygd-poller
            envVarPrefix: DB
        cascadingDelete: false