apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-infotrygd-poller
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
  kafka:
    pool: nav-prod
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 200m
      memory: 600Mi
  secureLogs:
    enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: hm-infotrygd-proxy.prod-fss-pub.nais.io
  gcp:
    sqlInstances:
      - name: hm-infotrygd-poller-db-prod
        type: POSTGRES_15
        tier: db-g1-small
        diskType: SSD
        highAvailability: true
        diskSize: 10
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: infotrygd-poller
            envVarPrefix: DB
        cascadingDelete: false
  env:
    - name: HTTP_PORT
      value: "8080"
    - name: RAPID_APP_NAME
      value: hm-infotrygd-poller
    - name: KAFKA_RAPID_TOPIC
      value: teamdigihot.hm-soknadsbehandling-v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: hm-infotrygd-poller-v1
    - name: KAFKA_RESET_POLICY
      value: latest
